---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


# hgchmagic

<!-- badges: start -->
<!-- badges: end -->

hgchmagic is a wrapper for highcharter R package. With hgchmagic you can provide more info in form of list and improve your visualizations.

The type of charts supported by hgchmagic are:

  - `hgch_bar()`
  - `hgch_line()`
  - `hgch_scatter()`
  - `hgch_treemap()`
  - `hgch_donut()`
  - `hgch_pie()`
  - `hgch_sankey()`

Everyone of them assist user with different treatment regarding data variable types. For example, for charts where categorical variables are involved, you can use:

  - `hgch_bar_Cat()`
  - `hgch_line_CatCat()`
  - `hgch_scatter_CatDatNum()`
  


## Installation

You can install the development version of hgchmagic like so:

``` r
# install.packages("devtools")
remotes::install_github("datasketch/hgchmagic")
```

## How to start

hgchmagic offers a several number of functions for interactive visualization. Check <a href="https://datasketch.github.io/hgchmagic/articles/hgchmagic.html" target="_blank">this article</a> or run `vignette("hgchmagic)` to see how hgchmagic works.


## Licence

hgchmagic depends on highcharter which is a wrapper for highcharts, a commercial JavaScript charting library. Highcharts offers both a commercial license as well as a free non-commercial license. Please review the licensing options and terms before using this software, as the highcharter license neither provides nor implies a license for Highcharts.

Highcharts (https://highcharts.com) is a Highsoft product which is not free for commercial and Governmental use.




